name: Discord PR Notify

on:
  pull_request:
    types:
      - opened
      - edited
      - closed
      
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "content":"PR更新: #${{ github.event.pull_request.number }}\n${{ github.event.pull_request.html_url }}"
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
